on:
  workflow_run:
    workflows: ["Update Fork"]
    types:
      - completed
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 2protec
          fetch-depth: 0
          token: ${{ secrets.PUSH }}

      - name: Setup Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Fetch changes from branch 2
        run: |
          git fetch origin 2

      - name: Merge changes from branch 2 into 2protec
        run: |
          git checkout 2protec
          git merge origin/2 --no-edit
          
      - name: Check for changes
        id: check_changes
        run: |
          CURRENT_COMMIT=$(git rev-parse HEAD)
          BRANCH_2_COMMIT=$(git rev-parse origin/2)
          if [ "$CURRENT_COMMIT" == "$BRANCH_2_COMMIT" ]; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: Push changes to 2protec
        if: steps.check_changes.outputs.has_changes == 'true'
        run: git push https://x-access-token:${{ secrets.PUSH }}@github.com/seichris/chatbot-ui.git 2protec

      - name: Create pull request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PUSH }}
          commit-message: Update 2protec with changes from branch 2
          title: Update 2protec with changes from branch 2
          body: |
            This pull request was automatically created to update the 2protec branch with the latest changes from the branch 2.
          branch: update-fork
          base: 2protec
